local addonName, addon = ...
addon.CHARATER_PANEL_ITEM_SLOTS_MAPPING = {}

addon.CHARATER_PANEL_ITEM_SLOTS_MAPPING[1] = "CharacterHeadSlot"
addon.CHARATER_PANEL_ITEM_SLOTS_MAPPING[2] = "CharacterNeckSlot"
addon.CHARATER_PANEL_ITEM_SLOTS_MAPPING[3] = "CharacterShoulderSlot"
addon.CHARATER_PANEL_ITEM_SLOTS_MAPPING[5] = "CharacterChestSlot"
addon.CHARATER_PANEL_ITEM_SLOTS_MAPPING[6] = "CharacterWaistSlot"
addon.CHARATER_PANEL_ITEM_SLOTS_MAPPING[7] = "CharacterLegsSlot"
addon.CHARATER_PANEL_ITEM_SLOTS_MAPPING[8] = "CharacterFeetSlot"
addon.CHARATER_PANEL_ITEM_SLOTS_MAPPING[9] = "CharacterWristSlot"
addon.CHARATER_PANEL_ITEM_SLOTS_MAPPING[10] = "CharacterHandsSlot"
addon.CHARATER_PANEL_ITEM_SLOTS_MAPPING[11] = "CharacterFinger0Slot"
addon.CHARATER_PANEL_ITEM_SLOTS_MAPPING[12] = "CharacterFinger1Slot"
addon.CHARATER_PANEL_ITEM_SLOTS_MAPPING[13] = "CharacterTrinket0Slot"
addon.CHARATER_PANEL_ITEM_SLOTS_MAPPING[14] = "CharacterTrinket1Slot"
addon.CHARATER_PANEL_ITEM_SLOTS_MAPPING[15] = "CharacterBackSlot"
addon.CHARATER_PANEL_ITEM_SLOTS_MAPPING[16] = "CharacterMainHandSlot"
addon.CHARATER_PANEL_ITEM_SLOTS_MAPPING[17] = "CharacterSecondaryHandSlot"
